---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-k8s-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-k8s-ns
  name: hello-k8s-deployment
  labels:
    app: hello-k8s
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: sasadangelo/hello-k8s
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
  namespace: hello-k8s-ns
spec:
  type: NodePort
  selector:
    app: hello-k8s
  ports:
    - protocol: TCP
      port: 80
