apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl
  MYSQL_USER: cm9vdA==  # root
  #MYSQL_USER: bXlzcWw= # mysql
