apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: drupal-mysql
  type: ClusterIP
