apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/drupal-data"
    type: Directory
