apiVersion: v1
kind: Service
metadata:
  labels:
    app: pento
  name: gop-fs-service
spec:
  ports:
  - name: pento
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: pento
  type: NodePort
